### PR TITLE
Modify nodes function in TreeLayout trait.

### PR DESCRIPTION
**Pull request by ababup1192**

### CODE REVIEW

**Comment by mathieuleclaire** [comment]
Hi,
thanks for your contribution. Did you test this modification properly the Nodes ?

**Comment by ababup1192** [comment]
Hi,
I wrote down a following code.
```
 val nodes = treeLayout.nodes(
          literal(name = "aaaa", children = js.Array()).asInstanceOf[GraphNode])
```
I passed.
But, A code which has children nest occur an stuck over flow error in native javascript codes.
```
 val nodes = treeLayout.nodes(
          literal(name = "aaaa", children = js.Array(literal(name = "bbbb", children = js.Array()))).asInstanceOf[GraphNode])
```
Please check such a code.

**Comment by ababup1192** [comment]
p.s.
This is a next code.
```
val links = treeLayout.links(nodes)
```

**Comment by mathieuleclaire** [comment]
Well, I cant't do some tests on it now, but tell me if it works better with the add of this pull request ?

**Comment by ababup1192** [comment]
I will make a new issue as you do it easily. If it works better, I will send a pull request.

**Pull request merged**
